@JournalChallenge.Presentation_HostAddress = http://localhost:5163

GET {{JournalChallenge.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.tree.get?treeName=TestTree
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.tree.node.create?treeName=TestTree&nodeName=Child1&parentNodeId=1
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.tree.node.rename?nodeId=2&newNodeName=RenamedChild
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.tree.node.delete?nodeId=2&isForcedDeletion=false
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.tree.node.delete?nodeId=2&isForcedDeletion=true
Accept: application/json

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.journal.getRange?skip=0&take=10
Content-Type: application/json

{}

###

POST {{JournalChallenge.Presentation_HostAddress}}/api.user.journal.getSingle?id=1
Accept: application/json

