<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JournalChallenge.Application\JournalChallenge.Application.csproj" />
      <ProjectReference Include="..\JournalChallenge.Domain\JournalChallenge.Domain.csproj" />
      <ProjectReference Include="..\JournalChallenge.Infrastructure\JournalChallenge.Infrastructure.csproj" />
      <ProjectReference Include="..\JournalChallenge.Presentation\JournalChallenge.Presentation.csproj" />
      <ProjectReference Include="..\JournalChallenge.Tests.Core\JournalChallenge.Tests.Core.csproj" />
    </ItemGroup>

</Project>
