services:
  db:
    image: postgres:18.2-alpine3.23
    environment:
      - POSTGRES_DB=journaldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d journaldb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  journalchallenge.presentation:
    image: journalchallenge.presentation
    build:
      context: .
      dockerfile: JournalChallenge.Presentation/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Database=journaldb;Username=postgres;Password=postgres
    healthcheck:
      test: [ "CMD-SHELL", "curl -fL http://localhost:8080/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 15
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
